[options]
library = "UMockdev"
version = "1.0"
min_cfg_version = "1.0"
target_path = "."
girs_directories = ["../gir-files/", ".."]
work_mode = "normal"
trust_return_value_nullability = true
single_version_file = true
generate_safety_asserts = true
deprecate_by_min_version = true

generate = [
    "UMockdev.Error",
    "UMockdev.IoctlBase",
    "UMockdev.IoctlClient",
    "UMockdev.IoctlData",
    "UMockdev.Testbed",
]
manual = [
    "GLib.Error",
]

external_libraries = [
    "GLib",
    "GObject",
]
