// Generated by gir (https://github.com/gtk-rs/gir @ 5327f5be4615)
// from .. (@ ???)
// from ../gir-files (@ 62da9eb7c4bd)
// DO NOT EDIT

#[cfg(not(docsrs))]
use std::process;

#[cfg(docsrs)]
fn main() {} // prevent linking libraries to avoid documentation failure

#[cfg(not(docsrs))]
fn main() {
    if let Err(s) = system_deps::Config::new().probe() {
        println!("cargo:warning={s}");
        process::exit(1);
    }
}
