// Generated by gir (https://github.com/gtk-rs/gir @ 5327f5be4615)
// from .. (@ ???)
// from ../gir-files (@ 62da9eb7c4bd)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "UMockdevError", sizeof(UMockdevError), alignof(UMockdevError));
    printf("%s;%zu;%zu\n", "UMockdevIoctlBase", sizeof(UMockdevIoctlBase), alignof(UMockdevIoctlBase));
    printf("%s;%zu;%zu\n", "UMockdevIoctlBaseClass", sizeof(UMockdevIoctlBaseClass), alignof(UMockdevIoctlBaseClass));
    printf("%s;%zu;%zu\n", "UMockdevIoctlClient", sizeof(UMockdevIoctlClient), alignof(UMockdevIoctlClient));
    printf("%s;%zu;%zu\n", "UMockdevIoctlClientClass", sizeof(UMockdevIoctlClientClass), alignof(UMockdevIoctlClientClass));
    printf("%s;%zu;%zu\n", "UMockdevIoctlData", sizeof(UMockdevIoctlData), alignof(UMockdevIoctlData));
    printf("%s;%zu;%zu\n", "UMockdevIoctlDataClass", sizeof(UMockdevIoctlDataClass), alignof(UMockdevIoctlDataClass));
    printf("%s;%zu;%zu\n", "UMockdevTestbed", sizeof(UMockdevTestbed), alignof(UMockdevTestbed));
    printf("%s;%zu;%zu\n", "UMockdevTestbedClass", sizeof(UMockdevTestbedClass), alignof(UMockdevTestbedClass));
    return 0;
}
